<?
$PERM["bitrix"]["8"]="D";
$PERM["bitrix"]["*"]="R";
$PERM["/"]["*"]="R";
$PERM["buyers_account"]["6"]="R";
$PERM["buyers_account"]["8"]="W";
$PERM["buyers_account"]["*"]="D";
$PERM["merchants_account"]["7"]="R";
$PERM["merchants_account"]["8"]="W";
$PERM["merchants_account"]["*"]="D";
$PERM["service"]["8"]="W";
$PERM["index.php"]["8"]="W";
$PERM["index.php"]["5"]="W";
$PERM["ads"]["8"]="W";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
?>