<?
$PERM["buyers_account"]["6"]="R";
$PERM["buyers_account"]["*"]="D";
$PERM["merchants_account"]["7"]="R";
$PERM["merchants_account"]["*"]="D";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>